name: Sentrey Release

on:
  release:
    types: [published]

# Make too releases since frontend/backend are in the same repo but two different sentry projects
jobs:
  createSentryRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create a Sentry.io release in oncokb-public-website
        uses: tclindner/sentry-releases-action@v1.0.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: memorial-sloan-kettering
          SENTRY_PROJECT: oncokb-public-website
        with:
          tagName: ${{ github.ref }}
          environment: production
          releaseNamePrefix: oncokb-public-
      - name: Create a Sentry.io release in oncokb-public-website-backend
        uses: tclindner/sentry-releases-action@v1.0.0
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: memorial-sloan-kettering
          SENTRY_PROJECT: oncokb-public-website-backend
        with:
          tagName: ${{ github.ref }}
          environment: production
          releaseNamePrefix: oncokb-public-backend-
